### ISSUE TITLE
mysql-export.json: problem with spaces 

### ISSUE THREAD

**Issue by farmascript** [MehbubRashid/vscode-one-click-mysql-export#1]
In the entry '"mysqlDumpDir"' in the file 'mysql-export.json' there is a problem with spaces in the value of mysqlDumpDir. 
I used a workaround by copying mysqldump.exe to a directory without spaces in the name.

Thnx for this very usefull utility!

**Comment by MehbubRashid** [comment]
Hi @farmascript , thanks for letting me know about the issue. I have fixed it and published a new version of the extension. If you like it, a rating would be much helpful :D Thanks

**Comment by farmascript** [comment]
Version 0.0.5
Now VSC gives a parse error:

```
ParserError:
Line |
   1 |  "C:\usr\progs\MariaDB 10.6\bin\mysqldump" -h localhost --port 3306 -u …
     |                                            ~~
     | Unexpected token '-h' in expression or statement.
```

**Comment by MehbubRashid** [comment]
Can you try in mysql server instead of mariadb?

**Comment by MehbubRashid** [comment]
Also please let me know if the same error appears when you use the workaround you used before?

**Comment by farmascript** [comment]
No mysql server installed.
The workaround gives now the same parse-error:
```
ParserError:
Line |
   1 |  "C:\usr\progs\mariaDB\mysqldump" -h localhost --port 3306 -u root -p  …
     |                                   ~~
     | Unexpected token '-h' in expression or statement.
```

**Comment by MehbubRashid** [comment]
I think you are using powershell. Please use CMD instead of powershell. Choose command prompt instead of powershell in the vscode terminal option.

**Comment by MehbubRashid** [comment]
Add`"terminal.integrated.defaultProfile.windows": "Command Prompt",` in your vscode settings.json

**Comment by farmascript** [comment]
Ok. That worked. Thnx!
Remains the fact that in the previous mysql-export version the work-around with powershell worked ok...

**Comment by MehbubRashid** [comment]
Let me explain why - 
when you have the mysqldump in a path that doesn't contain space, it works both in cmd and powershell.
when you have space in path, it doesn't work in either. The solution was to wrap the entire path in double quotes. Which i did in the latest version. But the problem is, this method only works in cmd. Powershell considers the command after double quotes wrong. So we had two options:-
* Using no space in folder path and both support cmd and powershell
* Allow space in folder path and only support CMD.
I think the second one is more suitable since you can easily change your default terminal in vscode. Its very common to contain space in path and we should allow it.

**Comment by farmascript** [comment]
Ok. Clairly explained!
Thnx for this very usefull extension!
